name: LeetParty
version: 1.0.0
author: "KyePlayzMCPE"
api: [2.0.0, 1.13.1]
main: LeetParty\KyePlayzMCPE\Main
description: ""
commands:
 lp:
    description: "Main Command for LP"
    usage: "/lp <create|delete|teleport|add|remove>"
    permission: lp.command
permissions:
  lp.command:
    default: true
    description: "Main Command for LP (Permission)"
    children:
      lp.command.create:
        default: true
        description: "Create a party (Permission)"
      lp.command.delete:
        default: true
        description: "Delete a party (Permission)"  
      lp.command.teleport:
        default: true
        description: "Teleport the party to you (Permission)"
      lp.command.add:
        default: true
        description: "Add a player to the party (Permission)"
      lp.command.remove:
        default: true
        description: "Remove a player from the party (Permission)"
